# Generated by Django 5.0 on 2025-11-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hpb_salon_id',
            field=models.CharField(blank=True, db_index=True, help_text='Extracted salon ID (e.g., H000123456)', max_length=20, verbose_name='HPB Salon ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='hpb_salon_url',
            field=models.URLField(blank=True, help_text='HPB salon top page URL (e.g., https://beauty.hotpepper.jp/slnH000xxxxx/)', max_length=500, verbose_name='HPB Salon URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='supabase_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='User ID from Supabase authentication system', max_length=255, null=True, unique=True, verbose_name='Supabase User ID'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['supabase_user_id'], name='accounts_us_supabas_36c5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['hpb_salon_id'], name='accounts_us_hpb_sal_fa4de1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='accounts_us_date_jo_ff39bb_idx'),
        ),
    ]
