# Generated by Django 5.0 on 2025-11-27 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_hpb_salon_id_user_hpb_salon_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address used for login attempt', max_length=254, verbose_name='Email')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the login was attempted', verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', verbose_name='User Agent')),
                ('success', models.BooleanField(help_text='Whether the login attempt was successful', verbose_name='Success')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for login failure (if applicable)', max_length=255, verbose_name='Failure Reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, help_text='User who attempted to login (null if user not found)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'db_table': 'accounts_login_attempt',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', '-timestamp'], name='accounts_lo_email_02dff7_idx'), models.Index(fields=['ip_address', '-timestamp'], name='accounts_lo_ip_addr_82ce5a_idx'), models.Index(fields=['success', '-timestamp'], name='accounts_lo_success_d2ca25_idx'), models.Index(fields=['-timestamp'], name='accounts_lo_timesta_a68562_idx')],
            },
        ),
    ]
