# -*- coding: utf-8 -*-
"""
Blog post models
"""

from django.db import models
from django.conf import settings


class BlogPost(models.Model):
    """
    Blog post model
    """
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('generating', 'AI Generating'),
        ('ready', 'Ready to Publish'),
        ('publishing', 'Publishing'),
        ('published', 'Published'),
        ('failed', 'Failed'),
    ]

    # Basic information
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='blog_posts',
        verbose_name='Author'
    )
    title = models.CharField(max_length=200, verbose_name='Title')
    content = models.TextField(verbose_name='Content')
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='draft',
        verbose_name='Status'
    )

    # AI generation related
    ai_prompt = models.TextField(
        blank=True,
        verbose_name='AI Prompt',
        help_text='Prompt sent to Gemini'
    )
    ai_generated = models.BooleanField(
        default=False,
        verbose_name='AI Generated',
        help_text='Whether this post was generated by AI'
    )

    # SALON BOARD posting related
    salon_board_url = models.URLField(
        blank=True,
        max_length=500,
        verbose_name='SALON BOARD URL',
        help_text='URL of the post on SALON BOARD'
    )
    published_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name='Published At'
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created At')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated At')

    class Meta:
        verbose_name = 'Blog Post'
        verbose_name_plural = 'Blog Posts'
        db_table = 'blog_post'
        ordering = ['-created_at']

    def __str__(self):
        return self.title


class SALONBoardAccount(models.Model):
    """
    SALON BOARD account information (encrypted)
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='salon_board_account',
        verbose_name='User'
    )
    email = models.EmailField(verbose_name='Email')
    encrypted_password = models.TextField(
        verbose_name='Encrypted Password',
        help_text='Password encrypted with Fernet'
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='Active',
        help_text='Whether this account is active'
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created At')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated At')

    class Meta:
        verbose_name = 'SALON BOARD Account'
        verbose_name_plural = 'SALON BOARD Accounts'
        db_table = 'salon_board_account'

    def __str__(self):
        return f"{self.user.username} - {self.email}"
