# Generated by Django 5.0 on 2025-11-25 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'AI Generating'), ('ready', 'Ready to Publish'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='Status')),
                ('ai_prompt', models.TextField(blank=True, help_text='Prompt sent to Gemini', verbose_name='AI Prompt')),
                ('ai_generated', models.BooleanField(default=False, help_text='Whether this post was generated by AI', verbose_name='AI Generated')),
                ('salon_board_url', models.URLField(blank=True, help_text='URL of the post on SALON BOARD', max_length=500, verbose_name='SALON BOARD URL')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SALONBoardAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('encrypted_password', models.TextField(help_text='Password encrypted with Fernet', verbose_name='Encrypted Password')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon_board_account', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'SALON BOARD Account',
                'verbose_name_plural': 'SALON BOARD Accounts',
                'db_table': 'salon_board_account',
            },
        ),
    ]
