# Generated by Django 5.0 on 2025-11-25 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='blog_images/%Y/%m/%d/', verbose_name='Image File')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0-based)', verbose_name='Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Blog Image',
                'verbose_name_plural': 'Blog Images',
                'db_table': 'blog_images',
                'ordering': ['blog_post', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('screenshot_path', models.CharField(blank=True, help_text='Path to completion screenshot', max_length=500, verbose_name='Screenshot Path')),
                ('scraping_data', models.JSONField(blank=True, default=dict, help_text='Data retrieved during scraping (JSON)', verbose_name='Scraping Data')),
                ('duration_seconds', models.IntegerField(default=0, help_text='Processing time in seconds', verbose_name='Duration (seconds)')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Post Log',
                'verbose_name_plural': 'Post Logs',
                'db_table': 'post_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveField(
            model_name='salonboardaccount',
            name='email',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID for async processing', max_length=255, verbose_name='Celery Task ID'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='coupon_name',
            field=models.CharField(blank=True, help_text='Coupon name for partial match search', max_length=100, verbose_name='Coupon Name'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='generated_content',
            field=models.TextField(blank=True, help_text='AI-generated original content (backup)', verbose_name='Generated Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords for content generation', max_length=200, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='stylist_id',
            field=models.CharField(blank=True, help_text='Stylist ID (T number, e.g., T000123456)', max_length=20, verbose_name='Stylist ID'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tone',
            field=models.CharField(blank=True, help_text='Tone and manner for content generation', max_length=50, verbose_name='Tone'),
        ),
        migrations.AddField(
            model_name='salonboardaccount',
            name='login_id',
            field=models.CharField(blank=True, default='', help_text='SALON BOARD login ID', max_length=255, verbose_name='Login ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Final content with image placeholders', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Datetime when post was published to SALON BOARD', null=True, verbose_name='Published At'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'AI Generating'), ('ready', 'Ready to Publish'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Blog title (max 25 characters)', max_length=25, verbose_name='Title'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['user', '-created_at'], name='blog_posts_user_id_9c9cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status'], name='blog_posts_status_795adf_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['celery_task_id'], name='blog_posts_celery__f0d370_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_at'], name='blog_posts_publish_12812e_idx'),
        ),
        migrations.AlterModelTable(
            name='blogpost',
            table='blog_posts',
        ),
        migrations.AlterModelTable(
            name='salonboardaccount',
            table='salon_board_accounts',
        ),
        migrations.AddField(
            model_name='blogimage',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogpost', verbose_name='Blog Post'),
        ),
        migrations.AddField(
            model_name='postlog',
            name='blog_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='blog.blogpost', verbose_name='Blog Post'),
        ),
        migrations.AddField(
            model_name='postlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='blogimage',
            index=models.Index(fields=['blog_post', 'order'], name='blog_images_blog_po_a8aec0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blogimage',
            unique_together={('blog_post', 'order')},
        ),
        migrations.AddIndex(
            model_name='postlog',
            index=models.Index(fields=['user', '-started_at'], name='post_logs_user_id_b1f878_idx'),
        ),
        migrations.AddIndex(
            model_name='postlog',
            index=models.Index(fields=['status'], name='post_logs_status_3d2cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='postlog',
            index=models.Index(fields=['-completed_at'], name='post_logs_complet_614518_idx'),
        ),
    ]
