# Generated by Django 5.0 on 2025-11-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogimage_postlog_remove_salonboardaccount_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlog',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=20, verbose_name='Status'),
        ),
    ]
