# Generated by Django 5.0 on 2025-11-26 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_selecting_status_and_variations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name to identify this template (e.g., "Standard Footer", "Campaign Info")', max_length=100, verbose_name='Template Name')),
                ('content', models.TextField(help_text='Footer text to append to blog posts (max 500 characters)', max_length=500, verbose_name='Template Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_templates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blog Post Template',
                'verbose_name_plural': 'Blog Post Templates',
                'db_table': 'blog_post_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='blogposttemplate',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_template_name_per_user'),
        ),
    ]
